services:
  web:
    build: .
    image: taller_internacional_web
    volumes:
      - taller_internacional_static_data:/app/staticfiles
      - taller_internacional_media_data:/app/media
    networks:
      - taller_internacional_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    volumes:
      - taller_internacional_mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/
    networks:
      - taller_internacional_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - taller_internacional_network
    depends_on:
      - db

networks:
  taller_internacional_network:
    driver: bridge

volumes:
  taller_internacional_mysql_data:
  taller_internacional_static_data:
  taller_internacional_media_data: