# Generated by Django 5.2.6 on 2025-11-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backuplog',
            options={'verbose_name': 'Registro de Respaldo', 'verbose_name_plural': 'Registros de Respaldos'},
        ),
        migrations.AddField(
            model_name='backuplog',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Error'),
        ),
        migrations.AlterModelTable(
            name='backuplog',
            table='backup_module_backuplog',
        ),
        migrations.AlterModelTable(
            name='configuracionrespaldo',
            table='backup_module_configuracionrespaldo',
        ),
    ]
