# Generated by Django 5.2.6 on 2025-12-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuplog',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Error/Advertencia'),
        ),
    ]
