# Generated by Django 5.2.6 on 2025-11-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_module', '0002_alter_backuplog_options_backuplog_mensaje_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuplog',
            name='mensaje_error',
        ),
    ]
