# Generated by Django 5.2.7 on 2025-12-01 15:08

import apy.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.IntegerField(unique=True, validators=[apy.models.validar_identificacion])),
                ('edad', models.PositiveIntegerField(validators=[apy.models.validar_edad])),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[apy.models.validar_email])),
                ('telefono', models.IntegerField(validators=[apy.models.validar_telefono])),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.BigIntegerField(validators=[apy.models.validar_identificacion])),
                ('telefono', models.BigIntegerField(validators=[apy.models.validar_telefono])),
                ('correo', models.EmailField(max_length=100, validators=[apy.models.validar_email])),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('inactivo', 'Desactivado')], default='semanal', max_length=10, verbose_name='Frecuencia')),
                ('hora_ejecucion', models.TimeField(default='03:00:00', verbose_name='Hora de Ejecución')),
            ],
            options={
                'verbose_name': 'Configuración de Respaldo',
                'verbose_name_plural': 'Configuraciones de Respaldo',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, validators=[apy.models.validar_telefono])),
                ('identificacion', models.CharField(max_length=20, unique=True, validators=[apy.models.validar_identificacion])),
                ('Correo', models.EmailField(max_length=254, unique=True, validators=[apy.models.validar_email])),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el costo.', 'required': 'El costo del insumo es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('stock', models.IntegerField()),
                ('cantidad', models.CharField(choices=[('galon', 'Galón'), ('litro', 'Litro'), ('mililitro', 'Mililitro'), ('unidades', 'Unidades')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Repuesto', 'Repuesto'), ('Herramienta', 'Herramienta'), ('Insumo', 'Insumo'), ('Vehiculo', 'Vehiculo')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Módulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Módulo de Permiso',
                'verbose_name_plural': 'Módulos de Permisos',
            },
        ),
        migrations.CreateModel(
            name='PagoServiciosPublicos',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('gas', 'Gas'), ('internet', 'Internet')], max_length=20)),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la nomina es obligatorio.'}, validators=[apy.models.validar_monto])),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, validators=[apy.models.validar_telefono])),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[apy.models.validar_email])),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('tipo', models.CharField(choices=[('Manual', 'Manual'), ('Automático', 'Automático')], max_length=10)),
                ('estado', models.CharField(choices=[('Éxito', 'Éxito'), ('Fallo', 'Fallo'), ('En Proceso', 'En Proceso')], default='En Proceso', max_length=10)),
                ('tamaño_mb', models.FloatField(blank=True, null=True, verbose_name='Tamaño (MB)')),
                ('ruta_archivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
            ],
            options={
                'verbose_name': 'Registro de Respaldo',
                'verbose_name_plural': 'Registros de Respaldo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='Taller Mecanica Diesel Internacional Arturo Patiño')),
                ('NIT', models.CharField(default='74.187366-2')),
                ('Dirección', models.CharField(default='calle 9 #32-37 Barrio La Isla')),
                ('Telefono', models.CharField(default='3118112714 - 3133342841', max_length=50)),
                ('Fecha', models.DateField()),
                ('Cliente', models.CharField(choices=[('cliente', 'Cliente'), ('empresa', 'Empresa')], max_length=50)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=50)),
                ('id_Detalles_servicios', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.PROTECT, to='apy.detalleservicio')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Venta', 'Venta'), ('Compra', 'Compra')], max_length=20)),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la caja es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.administrador')),
                ('id_Factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.factura')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.PositiveIntegerField(validators=[apy.models.validar_monto])),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.detalleservicio')),
                ('id_insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.insumos')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallas', models.TextField()),
                ('procesos', models.CharField(max_length=50)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.empleado')),
                ('id_tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.tipomantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='insumos',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.marca'),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('manuales', 'Manuales'), ('eléctricas', 'Eléctricas'), ('neumáticas', 'Neumáticas'), ('de medición', 'De Medición')], max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado')], max_length=100)),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la nomina es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('fecha_pago', models.DateField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del gasto es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('descripcion', models.TextField()),
                ('tipo_gastos', models.CharField(choices=[('costo fijo', 'Costo fijo'), ('costo directo', 'Costo directo'), ('costo variable', 'Costo variable')], max_length=100)),
                ('id_pagos_servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.pagoserviciospublicos')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('hora_compra', models.TimeField()),
                ('id_factura_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.factura')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('automotriz', 'Automotriz'), ('industrial', 'Industrial')], max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el precio.', 'required': 'El precio del repuesto es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del pago es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.administrador')),
                ('id_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.herramienta')),
                ('id_insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.insumos')),
                ('id_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.nomina')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.proveedores')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('repuestos_usados', models.TextField()),
                ('costo_mano_obra', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el costo de mano de obra.', 'required': 'El costo de mano de obra es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_informe', models.CharField(max_length=100)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.empleado')),
                ('id_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.mantenimiento')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.PositiveIntegerField(validators=[apy.models.validar_monto])),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.detalleservicio')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.PositiveIntegerField(validators=[apy.models.validar_monto])),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.detalleservicio')),
                ('id_tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener exactamente 6 caracteres alfanuméricos (letras mayúsculas o números).', regex='^[A-Z0-9]{6}$')])),
                ('modelo_vehiculo', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='El modelo debe ser un año válido de 4 dígitos (ej: 2024).', regex='^\\d{4}$')])),
                ('marca_vehiculo', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='La marca solo debe contener letras.', regex='^[A-Za-z\\s]+$')])),
                ('color', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El color solo debe contener letras.', regex='^[A-Za-z\\s]+$')])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaVehiculo',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo'),
        ),
        migrations.CreateModel(
            name='EntradaVehiculo',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False, verbose_name='Ver')),
                ('add', models.BooleanField(default=False, verbose_name='Crear')),
                ('change', models.BooleanField(default=False, verbose_name='Editar')),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminar')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.module', verbose_name='Módulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso Personalizado',
                'verbose_name_plural': 'Permisos Personalizados',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
