# Generated by Django 5.1.7 on 2026-02-23 23:08

import apy.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Venta', 'Venta'), ('Compra', 'Compra')], max_length=20)),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la caja es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('cliente particular', 'Cliente Particular'), ('empresa', 'Empresa')], max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre/Razón Social')),
                ('identificacion', models.CharField(max_length=50, unique=True, validators=[apy.models.validar_identificacion], verbose_name='Documento/NIT')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, validators=[apy.models.validar_email])),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Taller Mecanica Diesel Internacional Arturo Patiño', max_length=255)),
                ('nit', models.CharField(default='74.187366-2', max_length=50, validators=[django.core.validators.RegexValidator(message='El NIT debe tener el formato: 123456789-0 o 12.345.678-0', regex='^(\\d{1,3}(\\.?\\d{3}){2})\\-\\d$')])),
                ('direccion', models.CharField(default='calle 9 #32-37 Barrio La Isla', max_length=200)),
                ('telefono', models.CharField(default='3118112714 - 3133342841', max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaVehiculo',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el costo.', 'required': 'El costo del insumo es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('stock', models.IntegerField()),
                ('cantidad', models.CharField(choices=[('galon', 'Galón'), ('litro', 'Litro'), ('mililitro', 'Mililitro'), ('unidades', 'Unidades')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Repuesto', 'Repuesto'), ('Herramienta', 'Herramienta'), ('Insumo', 'Insumo'), ('Vehiculo', 'Vehiculo')], max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Módulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Módulo de Permiso',
                'verbose_name_plural': 'Módulos de Permisos',
            },
        ),
        migrations.CreateModel(
            name='PagoServiciosPublicos',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('gas', 'Gas'), ('internet', 'Internet')], max_length=20)),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la nomina es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, validators=[apy.models.validar_telefono])),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso por Protección Temporal')], max_length=5)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[apy.models.validar_email])),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaVehiculo',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.CharField(choices=[('terminado', 'Terminado'), ('proceso', 'En proceso')], default='proceso', max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.empresa')),
                ('id_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.entradavehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.PositiveIntegerField(validators=[apy.models.validar_monto])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.detalleservicio')),
                ('id_insumos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.insumos')),
            ],
        ),
        migrations.AddField(
            model_name='insumos',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.marca'),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('manuales', 'Manuales'), ('eléctricas', 'Eléctricas'), ('neumáticas', 'Neumáticas'), ('de medición', 'De Medición')], max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del gasto es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('descripcion', models.TextField()),
                ('tipo_gastos', models.CharField(choices=[('costo fijo', 'Costo fijo'), ('costo directo', 'Costo directo'), ('costo variable', 'Costo variable')], max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('id_pagos_servicios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.pagoserviciospublicos')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=11, null=True, validators=[apy.models.validar_identificacion])),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, validators=[apy.models.validar_telefono])),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tipo_informe', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], max_length=20)),
                ('costo_mano_obra', models.PositiveIntegerField(validators=[apy.models.validar_monto], verbose_name='Costo Mano de Obra')),
                ('total_repuestos', models.PositiveIntegerField(default=0, editable=False)),
                ('total_insumos', models.PositiveIntegerField(default=0, editable=False)),
                ('total_final', models.PositiveIntegerField(default=0, editable=False)),
                ('diagnostico_final', models.TextField(blank=True, null=True, verbose_name='Notas del Mecánico')),
                ('estado', models.BooleanField(default=True)),
                ('detalle_servicio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apy.detalleservicio', verbose_name='Detalle de Servicio')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.profile', verbose_name='Mecánico Responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('orden_servicio', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('repuestos', 'Repuestos'), ('insumos', 'Insumos')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.cliente')),
                ('detalle_servicio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='apy.detalleservicio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.profile')),
            ],
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.profile'),
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('automotriz', 'Automotriz'), ('industrial', 'Industrial')], max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el precio.', 'required': 'El precio del repuesto es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('estado', models.BooleanField(default=True)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del pago es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('estado', models.BooleanField(default=True)),
                ('id_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.herramienta')),
                ('id_insumos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.insumos')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.proveedores')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.PositiveIntegerField(validators=[apy.models.validar_monto])),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.detalleservicio')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.repuesto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='id_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.salidavehiculo'),
        ),
        migrations.CreateModel(
            name='DetalleTipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.PositiveIntegerField(validators=[apy.models.validar_monto])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.detalleservicio')),
                ('id_tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener exactamente 6 caracteres alfanuméricos (letras mayúsculas o números).', regex='^[A-Z0-9]{6}$')])),
                ('modelo_vehiculo', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='El modelo debe ser un año válido de 4 dígitos (ej: 2024).', regex='^\\d{4}$')])),
                ('marca_vehiculo', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='La marca solo debe contener letras.', regex='^[A-Za-z\\s]+$')])),
                ('color', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El color solo debe contener letras.', regex='^[A-Za-z\\s]+$')])),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallas', models.TextField()),
                ('procesos', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('id_empleado', models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.PROTECT, to='apy.profile')),
                ('id_tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.tipomantenimiento')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='apy.vehiculo'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False, verbose_name='Ver')),
                ('add', models.BooleanField(default=False, verbose_name='Crear')),
                ('change', models.BooleanField(default=False, verbose_name='Editar')),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminar')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.module', verbose_name='Módulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso Personalizado',
                'verbose_name_plural': 'Permisos Personalizados',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
