# Generated by Django 5.2.6 on 2026-03-06 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinsumos',
            name='detalle_servicio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.detalleservicio'),
        ),
        migrations.AlterField(
            model_name='detalleinsumos',
            name='id_insumos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.insumos'),
        ),
        migrations.AlterField(
            model_name='detallerepuesto',
            name='detalle_servicio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.detalleservicio'),
        ),
        migrations.AlterField(
            model_name='detallerepuesto',
            name='id_repuesto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.repuesto'),
        ),
        migrations.AlterField(
            model_name='detalletipomantenimiento',
            name='detalle_servicio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.detalleservicio'),
        ),
        migrations.AlterField(
            model_name='detalletipomantenimiento',
            name='id_tipo_mantenimiento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.tipomantenimiento'),
        ),
    ]
