# Generated by Django 5.2.6 on 2026-02-24 16:25
import apy.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
        model_name='detalleservicio',
        name='empleado',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.profile'),
    ),
    ]
