# Generated by Django 5.2.6 on 2025-11-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuplog',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ConfiguracionRespaldo',
        ),
        migrations.DeleteModel(
            name='BackupLog',
        ),
    ]
