# Generated by Django 5.2.6 on 2025-10-15 13:09

from django.db import migrations
from django.db.models import F

# Función que contiene la lógica para crear los registros de Module
def create_initial_modules(apps, schema_editor):
    # Obtenemos el modelo Module de la aplicación 'apy' en el estado actual de la migración
    Module = apps.get_model('apy', 'Module')

    print("\nCreando 19 módulos iniciales del sistema...")
    
    # ----------------------------------------------------
    # Módulos de Clientes y Movimiento (STEVEN)
    # ----------------------------------------------------
    Module.objects.get_or_create(name='Clientes', defaults={'description': 'Gestión de información de clientes.'})
    Module.objects.get_or_create(name='Vehiculos', defaults={'description': 'Gestión de la flota de vehículos.'})
    Module.objects.get_or_create(name='Entrada Vehiculo', defaults={'description': 'Registro de ingreso de vehículos al taller.'})
    Module.objects.get_or_create(name='Salida Vehiculo', defaults={'description': 'Registro de egreso y diagnóstico de vehículos.'})
    Module.objects.get_or_create(name='Caja', defaults={'description': 'Registro de movimientos de caja (Ingresos/Gastos).'})
    Module.objects.get_or_create(name='Compra', defaults={'description': 'Registro de las compras a proveedores.'})

    # ----------------------------------------------------
    # Módulos de Mantenimiento e Inventario (ERICK)
    # ----------------------------------------------------
    Module.objects.get_or_create(name='Tipo Mantenimiento', defaults={'description': 'Definición de tipos de mantenimiento (ej: cambio de aceite).'})
    Module.objects.get_or_create(name='Mantenimiento', defaults={'description': 'Gestión de fallas y procesos de reparación de vehículos.'})
    Module.objects.get_or_create(name='Marca', defaults={'description': 'Gestión de marcas de repuestos y herramientas.'})
    Module.objects.get_or_create(name='Repuestos', defaults={'description': 'Gestión del inventario de repuestos.'})
    Module.objects.get_or_create(name='Herramientas', defaults={'description': 'Gestión del inventario de herramientas.'})
    Module.objects.get_or_create(name='Insumos', defaults={'description': 'Gestión del inventario de insumos (líquidos, etc.).'})
    Module.objects.get_or_create(name='Informes', defaults={'description': 'Generación y consulta de informes de mantenimiento.'})

    # ----------------------------------------------------
    # Módulos Financieros y Administrativos (KAROL)
    # ----------------------------------------------------
    Module.objects.get_or_create(name='Administradores', defaults={'description': 'Gestión de administradores/gerentes.'})
    Module.objects.get_or_create(name='Empleados', defaults={'description': 'Gestión de información del personal.'})
    Module.objects.get_or_create(name='Nomina', defaults={'description': 'Gestión y registro de pagos de nómina.'})
    Module.objects.get_or_create(name='Proveedores', defaults={'description': 'Gestión de información de proveedores.'})
    Module.objects.get_or_create(name='Pagos', defaults={'description': 'Registro de pagos a proveedores y otros egresos.'})
    Module.objects.get_or_create(name='Servicios Públicos', defaults={'description': 'Registro de pagos de servicios públicos (Luz, Agua, Gas).'})
    Module.objects.get_or_create(name='Facturación', defaults={'description': 'Generación y consulta de facturas a clientes.'})


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'), # Asegúrate que este número de migración es correcto
    ]

    operations = [
        # Ejecuta la función de creación de datos
        migrations.RunPython(create_initial_modules, migrations.RunPython.noop),
    ]