# Generated by Django 5.2.6 on 2026-02-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informes',
            name='costo_mano_obra',
        ),
    ]
