# Generated by Django 5.2.6 on 2026-03-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stock disponible'),
        ),
    ]
