# Generated by Django 5.2.6 on 2026-01-27 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(default='000000', max_length=50, verbose_name='Documento/NIT'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(default='74.187366-2', max_length=50, validators=[django.core.validators.RegexValidator(message='El NIT debe tener el formato: 123456789-0 o 12.345.678-0', regex='^(\\d{1,3}(\\.?\\d{3}){2})\\-\\d$')]),
        ),
    ]
