# Generated by Django 5.2.6 on 2026-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='identificacion',
            field=models.CharField(default='POR_DEFINIR', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso por Protección Temporal')], default='cc', max_length=5),
            preserve_default=False,
        ),
    ]
