# Generated by Django 5.2.7 on 2025-10-09 12:06

import apy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='tipo',
            field=models.CharField(choices=[('Repuesto', 'Repuesto'), ('Herramienta', 'Herramienta'), ('Insumo', 'Insumo'), ('Vehiculo', 'Vehiculo')], max_length=100),
        ),
        migrations.CreateModel(
            name='DetalleRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del pago es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicio', models.CharField(max_length=100)),
                ('id_insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.insumos')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.repuesto')),
                ('id_tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.tipomantenimiento')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo')),
            ],
        ),
    ]
