# Generated by Django 5.2.6 on 2026-03-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
