# Generated by Django 5.1.7 on 2026-02-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='material',
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='insumos',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='insumos',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
