# Generated by Django 5.2.6 on 2025-10-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='categoria',
            field=models.CharField(choices=[('automotriz', 'Automotriz'), ('industrial', 'Industrial')], max_length=100),
        ),
    ]
