# Generated by Django 5.2.6 on 2026-03-05 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.proveedores'),
        ),
    ]
