# Generated by Django 5.2.6 on 2025-12-12 12:26

import apy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_auto_20251211_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='correo@gmail.com', max_length=254, validators=[apy.models.validar_email]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(default='sin', verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(default=63632267267, max_length=50, unique=True, verbose_name='Documento/NIT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='maria', max_length=255, verbose_name='Nombre/Razón Social'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=4374384378, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('cliente particular', 'Cliente Particular'), ('empresa', 'Empresa')], default='empresa', max_length=20),
            preserve_default=False,
        ),
    ]
