# Generated by Django 5.2.6 on 2026-03-04 21:31

import apy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_alter_herramienta_stock_alter_insumos_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='gastos',
            name='id_pagos_servicios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apy.pagoserviciospublicos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='stock',
            field=models.PositiveIntegerField(validators=[apy.models.validar_stock], verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='stock',
            field=models.PositiveIntegerField(validators=[apy.models.validar_stock], verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[apy.models.validar_monto]),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock',
            field=models.PositiveIntegerField(validators=[apy.models.validar_stock], verbose_name='Stock disponible'),
        ),
    ]
