# Generated by Django 5.2.6 on 2026-03-05 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_alter_gastos_id_pago_alter_gastos_nomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='id_pagos_servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.pagoserviciospublicos'),
        ),
    ]
