# Generated by Django 5.2.6 on 2026-03-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_alter_repuesto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
