# Generated by Django 5.2.6 on 2026-02-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_detalleservicio_id_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.empresa'),
        ),
    ]
