# Generated by Django 5.2.6 on 2026-02-20 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_auto_20251015_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informes',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.PROTECT, to='apy.profile'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.PROTECT, to='apy.profile'),
        ),
    ]
