# Generated by Django 5.2.6 on 2026-01-27 22:54

import apy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_alter_cliente_identificacion_alter_empresa_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=50, unique=True, validators=[apy.models.validar_identificacion], verbose_name='Documento/NIT'),
        ),
    ]
