# Generated by Django 5.2.6 on 2026-02-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_auto_20251015_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso de Protección Temporal')], default='CC', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
