# Generated by Django 5.1.7 on 2026-02-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_proveedores_identificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleservicio',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='entradavehiculo',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='entradavehiculo',
            name='id_vehiculo',
        ),
        migrations.RemoveField(
            model_name='salidavehiculo',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='salidavehiculo',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='salidavehiculo',
            name='id_vehiculo',
        ),
    ]
