# Generated by Django 5.2.6 on 2026-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_remove_informes_costo_mano_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerepuesto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
