# Generated by Django 5.2.6 on 2025-10-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_repuesto_subcategoria_alter_repuesto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='id_repuestos',
            new_name='id_repuesto',
        ),
    ]
