# Generated by Django 5.2.6 on 2025-10-15 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_auto_20251015_0809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permiso Personalizado', 'verbose_name_plural': 'Permisos Personalizados'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='add',
            field=models.BooleanField(default=False, verbose_name='Crear'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='change',
            field=models.BooleanField(default=False, verbose_name='Editar'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Eliminar'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.module', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='view',
            field=models.BooleanField(default=False, verbose_name='Ver'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('user', 'module')},
        ),
    ]
