# Generated by Django 5.2.6 on 2026-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_detallerepuesto_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinsumos',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
