# Generated by Django 5.2.6 on 2025-10-21 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_rename_id_repuestos_pagos_id_repuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='subcategoria',
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='tipo',
            field=models.CharField(choices=[('manuales', 'Manuales'), ('eléctricas', 'Eléctricas'), ('neumáticas', 'Neumáticas'), ('de medición', 'De Medición')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener exactamente 6 caracteres alfanuméricos (letras mayúsculas o números).', regex='^[A-Z0-9]{6}$')]),
        ),
    ]
