# Generated by Django 5.2.6 on 2026-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_remove_caja_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso por Protección Temporal')], default='CC', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('credito', 'Crédito')], max_length=20),
        ),
    ]
