# Generated by Django 5.2.6 on 2026-02-15 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_detalleservicio_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='id_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.salidavehiculo'),
        ),
    ]
