# Generated by Django 5.1.7 on 2026-02-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_remove_detalleservicio_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.profile'),
        ),
    ]
