# Generated by Django 5.2.7 on 2025-11-11 03:30

import apy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_alter_administrador_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Está activo'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='monto',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del gasto es obligatorio.'}, validators=[apy.models.validar_monto]),
        ),
        migrations.AlterField(
            model_name='informes',
            name='costo_mano_obra',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el costo de mano de obra.', 'required': 'El costo de mano de obra es obligatorio.'}, validators=[apy.models.validar_monto]),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='costo',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el costo.', 'required': 'El costo del insumo es obligatorio.'}, validators=[apy.models.validar_monto]),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='monto',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la nomina es obligatorio.'}, validators=[apy.models.validar_monto]),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='monto',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del pago es obligatorio.'}, validators=[apy.models.validar_monto]),
        ),
        migrations.AlterField(
            model_name='pagoserviciospublicos',
            name='monto',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la nomina es obligatorio.'}, validators=[apy.models.validar_monto]),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el precio.', 'required': 'El precio del repuesto es obligatorio.'}, validators=[apy.models.validar_monto]),
        ),
    ]
