# Generated by Django 5.2.6 on 2026-02-26 02:23

import apy.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0004_detalleinsumos_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gastos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='caja',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto',
            field=models.IntegerField(validators=[apy.models.validar_monto]),
        ),
        migrations.AlterField(
            model_name='caja',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Nomina', 'Nomina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.herramienta'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_insumos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.insumos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.repuesto'),
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(validators=[apy.models.validar_monto])),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apy.profile')),
            ],
        ),
    ]
