# Generated by Django 5.2.6 on 2026-02-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0004_detalleservicio_id_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='proceso',
            field=models.CharField(choices=[('terminado', 'Terminado'), ('proceso', 'En proceso')], default='proceso', max_length=20),
        ),
    ]
