# Generated by Django 5.2.6 on 2026-02-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_alter_gastos_monto_alter_informes_costo_mano_obra_and_more'),
        ('apy', '0004_auto_20260202_0745'),
    ]

    operations = [
    ]
