# Generated by Django 5.2.6 on 2026-03-04 23:45

import apy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0004_cliente_tipo_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, validators=[apy.models.validar_telefono]),
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
    ]
