# Generated by Django 5.2.6 on 2025-12-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0004_remove_cliente_monto_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, default='perfiles/default.png', null=True, upload_to='perfiles/'),
        ),
    ]
