# Generated by Django 5.2.6 on 2025-10-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0004_remove_repuesto_subcategoria_alter_herramienta_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='tipo_gastos',
            field=models.CharField(choices=[('Costo fijo', 'costo fijo'), ('Costo directo', 'costo directo'), ('Costo variable', 'costo variable')], max_length=100),
        ),
    ]
