# Generated by Django 5.2.6 on 2025-10-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0005_alter_gastos_tipo_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='tipo_gastos',
            field=models.CharField(choices=[('costo fijo', 'Costo fijo'), ('costo directo', 'Costo directo'), ('costo variable', 'Costo variable')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado')], max_length=100),
        ),
    ]
