# Generated by Django 5.2.6 on 2026-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0005_alter_cliente_correo_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleservicio',
            old_name='vehiculo',
            new_name='id_vehiculo',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(),
        ),
    ]
