# Generated by Django 5.2.6 on 2026-02-26 04:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0005_caja_descripcion_gastos_fecha_alter_caja_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='id_proveedor',
            new_name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='id_herramienta',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='id_insumos',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='id_repuesto',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='tipo_pago',
        ),
        migrations.AddField(
            model_name='pagos',
            name='monto_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('Repuesto', 'Repuesto'), ('Insumo', 'Insumo'), ('Herramienta', 'Herramienta')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.IntegerField()),
                ('herramienta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.herramienta')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.insumos')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='apy.pagos')),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.repuesto')),
            ],
        ),
    ]
