# Generated by Django 5.2.6 on 2026-02-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0005_merge_20260209_0813'),
        ('apy', '0006_rename_vehiculo_detalleservicio_id_vehiculo_and_more'),
    ]

    operations = [
    ]
