# Generated by Django 5.2.6 on 2026-02-26 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0006_rename_id_proveedor_pagos_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('credito', 'Crédito')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.herramienta'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.insumos'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='apy.pagos'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.repuesto'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.profile'),
        ),
    ]
