# Generated by Django 5.2.6 on 2026-02-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_auto_20251015_0809'),
        ('apy', '0006_detalleinsumos_subtotal_detallerepuesto_subtotal_and_more'),
    ]

    operations = [
    ]
