# Generated by Django 5.2.6 on 2026-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0007_merge_20260211_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='id_admin',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
