# Generated by Django 5.2.6 on 2026-02-27 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0007_pagos_tipo_pago_alter_detallepago_herramienta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletipomantenimiento',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_realizados', to='apy.profile', verbose_name='Mecánico Responsable'),
        ),
    ]
