# Generated by Django 5.2.6 on 2026-02-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0007_merge_20260220_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallerepuesto',
            name='subtotal',
        ),
    ]
