# Generated by Django 5.2.6 on 2026-02-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0008_detalletipomantenimiento_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='id_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.pagos'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.nomina'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='id_pagos_servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apy.pagoserviciospublicos'),
        ),
    ]
