# Generated by Django 5.2.6 on 2026-02-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0008_remove_detallerepuesto_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleservicio',
            name='cliente',
        ),
    ]
