# Generated by Django 5.2.6 on 2026-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0009_gastos_id_pago_gastos_nomina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
