# Generated by Django 5.2.6 on 2026-02-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0009_remove_detalleservicio_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apy.cliente'),
            preserve_default=False,
        ),
    ]
