# Generated by Django 5.2.6 on 2026-02-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0010_detalleservicio_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleservicio',
            old_name='cliente',
            new_name='cliente_nuevo',
        ),
    ]
