# Generated by Django 5.2.6 on 2026-02-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0010_nomina_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=2, verbose_name='Stock mínimo'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock mínimo'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock mínimo'),
        ),
    ]
