# Generated by Django 5.2.6 on 2026-02-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0011_rename_cliente_detalleservicio_cliente_nuevo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleservicio',
            old_name='cliente_nuevo',
            new_name='cliente',
        ),
    ]
