# Generated by Django 5.2.6 on 2026-03-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0011_herramienta_stock_herramienta_stock_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Repuesto', 'Repuesto'), ('Insumo', 'Insumo'), ('Herramienta', 'Herramienta')], max_length=20)),
                ('nombre_item', models.CharField(max_length=200)),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('nivel', models.CharField(choices=[('sin_stock', 'Sin Stock'), ('stock_bajo', 'Stock Bajo')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock mínimo'),
        ),
    ]
