# Generated by Django 5.2.6 on 2026-02-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0012_rename_cliente_nuevo_detalleservicio_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='orden_servicio',
        ),
    ]
