# Generated by Django 5.2.6 on 2026-03-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_auto_20251015_0809'),
        ('apy', '0012_alertastock_alter_repuesto_stock_minimo'),
    ]

    operations = [
    ]
