# Generated by Django 5.2.6 on 2026-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0013_remove_factura_orden_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='orden_servicio',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('repuestos', 'Repuestos'), ('insumos', 'Insumos')], default='000', max_length=20),
            preserve_default=False,
        ),
    ]
