# Generated by Django 5.2.6 on 2026-03-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0013_merge_20260302_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradavehiculo',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='apy.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='entradavehiculo',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='apy.vehiculo', verbose_name='Vehículo'),
        ),
    ]
