# Generated by Django 5.2.6 on 2026-02-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0014_factura_orden_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleinsumos',
            name='subtotal',
        ),
    ]
