# Generated by Django 5.2.6 on 2026-03-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0014_entradavehiculo_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepago',
            name='unidad',
            field=models.CharField(blank=True, choices=[('galon', 'Galón'), ('litro', 'Litro'), ('mililitro', 'Mililitro'), ('unidades', 'Unidades')], max_length=20, null=True, verbose_name='Unidad de medida'),
        ),
    ]
