# Generated by Django 5.2.6 on 2026-03-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0015_detallepago_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='servicios', to='apy.cliente'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='empleado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='apy.profile'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='empresa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='apy.empresa'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='id_entrada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='apy.entradavehiculo'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='id_salida',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='apy.salidavehiculo'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='id_vehiculo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='servicios', to='apy.vehiculo'),
        ),
    ]
