# Generated by Django 5.2.6 on 2026-02-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0015_remove_detalleinsumos_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='identificacion',
            new_name='identificacion_n',
        ),
    ]
