# Generated by Django 5.2.6 on 2026-02-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0016_rename_identificacion_profile_identificacion_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='identificacion_n',
            new_name='identificacion',
        ),
    ]
