"""
Django settings for taller project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path
from pyexpat.errors import messages
from dotenv import load_dotenv
from django.contrib.messages import constants as messages


# Cargar variables del entorno ANTES de cualquier configuración
load_dotenv()

print("EMAIL USER:", os.environ.get('EMAIL_HOST_USER', 'NO CARGADO'))
print("ADMINS STOCK:", os.environ.get('ADMINS_CORREO_STOCK', 'NO CARGADO'))
print(f"DEBUG: DB_NAME={os.getenv('DB_NAME')}")
print(f"DEBUG: DB_HOST={os.getenv('DB_HOST')}")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- Configuración del Módulo de Backup ---
# Define la ruta donde se guardarán los backups, dentro del directorio base.
BACKUP_ROOT = BASE_DIR / 'db_backups' # Usé 'db_backups' por claridad
try:
    # Asegúrate de que la carpeta exista y sea escribible.
    Path(BACKUP_ROOT).mkdir(parents=True, exist_ok=True)
except OSError as e:
    # Es bueno loguear si no se pudo crear el directorio.
    logging.error(f"No se pudo crear el directorio de backups en {BACKUP_ROOT}: {e}")
# -------------------------------------------


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# En settings.py:
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'taller_internacional.artisandev.site', 'web', 'db']
CSRF_TRUSTED_ORIGINS = ['https://taller_internacional.artisandev.site']
WHITENOISE_MANIFEST_STRICT = False
# TEMPORAL para debug — quítalo cuando funcione

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', 
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'apy',
    'login',
    'widget_tweaks',
    'backup_module',
    'axes',
    'ia_assistant',
    'django_recaptcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # Enable WhiteNoise middleware for serving static files
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apy.middleware.DisableBrowserCacheMiddleware', # <--- AQUÍ
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'taller.urls'

TEMPLATES = [
    
    {
        
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # Nuestro context processor personalizado para permisos de usuario
                'apy.context_processors.user_permissions',
                
                'apy.context_processors.alertas_stock',   
            ],
        },
    },
]

WSGI_APPLICATION = 'taller.wsgi.application'
# settings.py (CONFIGURACIÓN PERMANENTE MYSQL)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('DB_PORT', '3306'),
    },
    
    'log_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_LOG_NAME', 'bckp_logs'),
        'USER': os.getenv('DB_USER'), 
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('DB_PORT', '3306'), 
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

DATABASE_ROUTERS = ['backup_module.routers.LogRouter']
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# En tu settings.py busca AUTH_PASSWORD_VALIDATORS y asegúrate de que se vea así:
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'login.validators.ComplexPasswordValidator',
    },
    {
        'NAME': 'apy.validators.ComplexPasswordValidator',
    },
]


# El enlace de recuperación de contraseña expirará en 24 horas
PASSWORD_RESET_TIMEOUT = 86400

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",  # ← bcrypt + SHA256 (recomendado)
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",        # fallback por si acaso
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = 5          # 5 intentos fallidos → bloqueo
AXES_COOLOFF_TIME = timedelta(minutes=1)
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]
AXES_LOCKOUT_TEMPLATE = 'lock_out.html'
AXES_LOCKOUT_CALLABLE = 'login.views.axes_lockout_view'
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

USE_TZ = True # Asegura que Django use zonas horarias

TIME_ZONE = 'America/Bogota' # Establece la zona horaria a Colombia

USE_I18N = True

USE_L10N = True

# La línea USE_TZ = True ya está arriba, la dejamos
# USE_TZ = True

MESSAGE_TAGS = {
    messages.DEBUG:   'secondary',
    messages.INFO:    'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR:   'danger',   # Bootstrap usa 'danger', no 'error'
}
# -----------------------------------------------------
## 📁 Configuración de Archivos Estáticos (STATIC)
# -----------------------------------------------------
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'apy', 'static'),
    os.path.join(BASE_DIR, 'login', 'static'), 
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# -----------------------------------------------------
## 🖼️ Configuración de Archivos de Usuario (MEDIA)
# -----------------------------------------------------
# La URL que usaremos para acceder a los archivos subidos (ej: la foto de perfil)
MEDIA_URL = '/media/'
# La ruta física donde Django guarda los archivos subidos (dentro del proyecto)
MEDIA_ROOT = BASE_DIR / 'media'
# -----------------------------------------------------


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login:login'
LOGIN_REDIRECT_URL = 'apy:estadisticas'
LOGOUT_REDIRECT_URL = ''

# -----------------------------------------------------
# ✅ CONFIGURACIÓN DE CORREO
# -----------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'soportecnico.t.i.m@gmail.com'
EMAIL_HOST_PASSWORD = 'aocumubtnqxvccbb'
EMAIL_HOST_PASSWORD = 'vwnifvdwehnmpodg'
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER                        
ADMINS_CORREO_STOCK = 'yury45884@gmail.com'    

# -----------------------------------------------------
# 📦 WhiteNoise y Almacenamiento
# -----------------------------------------------------
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# La duplicación de MEDIA_URL y MEDIA_ROOT ha sido eliminada de aquí

# Captcha
RECAPTCHA_PUBLIC_KEY = '6LfxrX8sAAAAAL0qNDnErnyfY7SqlUV61EdDMxUp'
RECAPTCHA_PRIVATE_KEY = '6LfxrX8sAAAAAIDWOhXp7iBZAT4GDhNKOKLuv_eR'
SILENT_RECAPTCHA_FIELDS = True