"""
Django settings for taller project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Cargar variables del entorno ANTES de cualquier configuración
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Configuración del Módulo de Backup ---
# Define la ruta donde se guardarán los backups, dentro del directorio base.
BACKUP_ROOT = BASE_DIR / 'db_backups' # Usé 'db_backups' por claridad
try:
    # Asegúrate de que la carpeta exista y sea escribible.
    Path(BACKUP_ROOT).mkdir(parents=True, exist_ok=True)
except OSError as e:
    # Es bueno loguear si no se pudo crear el directorio.
    logging.error(f"No se pudo crear el directorio de backups en {BACKUP_ROOT}: {e}")
# -------------------------------------------


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ras&$usy0ocn2u-x=k00^w8o1zda_&vu41u68h3p+(7_*ween'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'apy',
    'login',
    'widget_tweaks',
    
    'backup_module',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'taller.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taller.wsgi.application'
# settings.py (CONFIGURACIÓN PERMANENTE MYSQL)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'mydatabase'),
        'USER': os.getenv('DB_USER', 'myuser'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'mypassword'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3307'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

USE_TZ = True # Asegura que Django use zonas horarias

TIME_ZONE = 'America/Bogota' # Establece la zona horaria a Colombia

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles", # Añade esta línea
    BASE_DIR / 'apy' / 'static' / 'AdminLTE' / 'dist',
]
#eSTATIC_ROOT = BASE_DIR / "staticfiles"#Esta variable solo se usa en produccion

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login:login'
LOGIN_REDIRECT_URL = 'apy:informes_lista'
LOGOUT_REDIRECT_URL = ''

# -----------------------------------------------------
# ✅ CONFIGURACIÓN DE CORREO CORREGIDA Y FINAL
# -----------------------------------------------------
# Asegúrate de que esta línea esté presente:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
# Si usas Gmail (lo más común):
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'soportecnico.t.i.m@gmail.com'
EMAIL_HOST_PASSWORD = 'pjqmmdgfnredlrtg'

# -----------------------------------------------------
# ✅ CONFIGURACIÓN DE ARCHIVOS MEDIA (Para Backups)
# -----------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -----------------------------------------------------
# ✅ CONFIGURACIÓN DE CELERY (Tareas Asíncronas)
# -----------------------------------------------------
# Utilizando Redis como broker (el más común)
# Asegúrate de que Redis esté corriendo en 127.0.0.1:6379
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' 
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0' # Para rastrear el resultado de las tareas

# Configuración de serialización (para seguridad y compatibilidad)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Usa la misma zona horaria de Django
CELERY_TIMEZONE = 'America/Bogota' 

# Indica que Celery Beat debe leer la programación de la base de datos (modelo PeriodicTask)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
