# Generated by Django 5.2.6 on 2025-09-11 15:06

import apy.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.IntegerField(max_length=11, unique=True, validators=[apy.models.validar_identificacion])),
                ('edad', models.PositiveIntegerField(validators=[apy.models.validar_edad])),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[apy.models.validar_email])),
                ('telefono', models.IntegerField(max_length=10, validators=[apy.models.validar_telefono])),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.BigIntegerField(validators=[apy.models.validar_identificacion])),
                ('telefono', models.BigIntegerField(validators=[apy.models.validar_telefono])),
                ('correo', models.EmailField(max_length=100, validators=[apy.models.validar_email])),
                ('fecha_operacion', models.DateField()),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del cliente es obligatorio.'}, validators=[apy.models.validar_monto])),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, validators=[apy.models.validar_telefono])),
                ('identificacion', models.CharField(max_length=20, unique=True, validators=[apy.models.validar_identificacion])),
                ('Correo', models.EmailField(max_length=254, unique=True, validators=[apy.models.validar_email])),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PagoServiciosPublicos',
            fields=[
                ('servicio', models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('gas', 'Gas'), ('internet', 'Internet')], max_length=20)),
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la nomina es obligatorio.'}, validators=[apy.models.validar_monto])),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, validators=[apy.models.validar_telefono])),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[apy.models.validar_email])),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=45)),
                ('servicio_prestado', models.CharField(max_length=45)),
                ('nombre_empresa', models.CharField(max_length=45)),
                ('direccion_empresa', models.CharField(max_length=45)),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la factura es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.empleado')),
                ('id_tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la caja es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.administrador')),
                ('id_Factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallas', models.TextField()),
                ('procesos', models.CharField(max_length=50)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.empleado')),
                ('id_tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el costo.', 'required': 'El costo del insumo es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('tipo', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto de la nomina es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('fecha_pago', models.DateField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del gasto es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('descripcion', models.TextField()),
                ('tipo_gastos', models.CharField(max_length=100)),
                ('id_pagos_servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.pagoserviciospublicos')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('hora_compra', models.TimeField()),
                ('id_factura_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.factura')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el precio.', 'required': 'El precio del repuesto es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el monto.', 'required': 'El monto del pago es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.administrador')),
                ('id_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.herramienta')),
                ('id_insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.insumos')),
                ('id_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.nomina')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.proveedores')),
                ('id_repuestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('repuestos_usados', models.TextField()),
                ('costo_mano_obra', models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el costo de mano de obra.', 'required': 'El costo de mano de obra es obligatorio.'}, validators=[apy.models.validar_monto])),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_informe', models.CharField(max_length=100)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.empleado')),
                ('id_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.mantenimiento')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener el formato ABC123 (3 letras seguidas de 3 números).', regex='^[A-Z]{3}\\d{3}$')])),
                ('modelo_vehiculo', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='El modelo debe ser un año válido de 4 dígitos (ej: 2024).', regex='^\\d{4}$')])),
                ('marca_vehiculo', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='La marca solo debe contener letras.', regex='^[A-Za-z\\s]+$')])),
                ('color', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El color solo debe contener letras.', regex='^[A-Za-z\\s]+$')])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaVehiculo',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo'),
        ),
        migrations.CreateModel(
            name='EntradaVehiculo',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo')),
            ],
        ),
    ]
