# Generated by Django 5.2.4 on 2025-08-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('id_operacion', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.BigIntegerField(default=0)),
                ('telefono', models.BigIntegerField(default=0)),
                ('correo', models.EmailField(max_length=100)),
                ('fecha_operacion', models.DateField()),
                ('monto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('tipo_gastos', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_marca', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PagoServiciosPublicos',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(blank=True, max_length=45, null=True)),
                ('servicio_prestado', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion_empresa', models.CharField(blank=True, max_length=45, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.cliente')),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.empleado')),
                ('id_tipo_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallas', models.TextField()),
                ('procesos', models.CharField(max_length=50)),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.empleado')),
                ('id_tipo_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('id_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.administrador')),
                ('id_herramienta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.herramienta')),
                ('id_insumos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.insumos')),
                ('id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.administrador')),
                ('id_Factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.factura')),
                ('id_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.gastos')),
                ('id_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.nomina')),
                ('id_pagos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.pagos')),
            ],
        ),
        migrations.AddField(
            model_name='gastos',
            name='id_pagos_servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.pagoserviciospublicos'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('id_factura_compra', models.IntegerField(unique=True)),
                ('fecha_compra', models.DateField()),
                ('hora_compra', models.TimeField()),
                ('id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('id_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.marca')),
            ],
        ),
        migrations.AddField(
            model_name='pagos',
            name='id_repuestos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.repuesto'),
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('repuestos_usados', models.TextField()),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_informe', models.CharField(max_length=100)),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.empleado')),
                ('id_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.mantenimiento')),
                ('id_repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo_vehiculo', models.CharField(max_length=100)),
                ('marca_vehiculo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaVehiculo',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
                ('id_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.vehiculo'),
        ),
        migrations.CreateModel(
            name='EntradaVehiculo',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
                ('id_vehiculo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo')),
            ],
        ),
    ]
