# Generated by Django 5.2.4 on 2025-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoserviciospublicos',
            name='servicio',
            field=models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('gas', 'Gas'), ('internet', 'Internet')], default='luz', max_length=20),
        ),
    ]
