# Generated by Django 5.2.4 on 2025-09-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='insumos',
            name='tipo',
        ),
    ]
