# Generated by Django 5.2.4 on 2025-07-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(unique=True)),
                ('id_operacion', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.BigIntegerField(default=0)),
                ('telefono', models.BigIntegerField(default=0)),
                ('correo', models.EmailField(max_length=100)),
                ('fecha_operacion', models.DateField()),
                ('monto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura_compra', models.IntegerField(unique=True)),
                ('id_compra', models.IntegerField(default=0)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha_compra', models.DateField()),
                ('hora_compra', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo_gastos', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_marca', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PagoServiciosPublicos',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='equipo',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='descripcion',
            new_name='fallas',
        ),
        migrations.RenameField(
            model_name='repuesto',
            old_name='nombre',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='realizado_por',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tipomantenimiento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_tipo_mantenimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apy.tipomantenimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='procesos',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='fabricante',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='ubicacion',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipomantenimiento',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apy.empleado'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(blank=True, max_length=45, null=True)),
                ('servicio_prestado', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion_empresa', models.CharField(blank=True, max_length=45, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.cliente')),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.empleado')),
                ('id_tipo_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('repuestos_usados', models.TextField()),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_informe', models.CharField(max_length=100)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.empleado')),
                ('id_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.mantenimiento')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.marca')),
            ],
        ),
        migrations.AddField(
            model_name='repuesto',
            name='id_marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apy.marca'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.administrador')),
                ('id_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.herramienta')),
                ('id_insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.insumos')),
                ('id_repuestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.repuesto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.administrador')),
                ('id_Factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.factura')),
                ('id_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.gastos')),
                ('id_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.nomina')),
                ('id_pagos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.pagos')),
            ],
        ),
        migrations.AddField(
            model_name='gastos',
            name='id_pagos_servicios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.pagoserviciospublicos'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vehiculo', models.IntegerField(unique=True)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo_vehiculo', models.CharField(max_length=100)),
                ('marca_vehiculo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.vehiculo'),
        ),
        migrations.CreateModel(
            name='EntradaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
