# Generated by Django 5.2.4 on 2025-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='id_vehiculo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
