# Generated by Django 5.2.6 on 2025-10-02 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_module_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='can_add',
            new_name='add',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='can_change',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='can_delete',
            new_name='delete',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='can_view',
            new_name='view',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perms', to='apy.module'),
        ),
    ]
