# Generated by Django 5.2.4 on 2025-08-19 12:45

import apy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_repuesto_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, validators=[apy.models.validar_email]),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, validators=[apy.models.validar_email]),
        ),
    ]
