# Generated by Django 5.2.4 on 2025-07-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_administrador_cliente_compra_empleado_gastos_insumos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='Correo',
            new_name='correo',
        ),
    ]
