# Generated by Django 5.2.4 on 2025-07-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_remove_vehiculo_id_alter_vehiculo_id_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidavehiculo',
            old_name='id_vehiculo',
            new_name='idss_vehiculo',
        ),
    ]
