# Generated by Django 5.2.4 on 2025-07-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_administrador_cliente_compra_empleado_gastos_insumos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informes',
            name='id_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.empleado'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='id_mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.mantenimiento'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='id_repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.repuesto'),
        ),
    ]
