# Generated by Django 5.2.4 on 2025-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_alter_tipomantenimiento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
