# Generated by Django 5.2.4 on 2025-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0002_pagoserviciospublicos_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoserviciospublicos',
            name='servicio',
            field=models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('gas', 'Gas'), ('internet', 'Internet')], max_length=20),
        ),
    ]
