# Generated by Django 5.2.4 on 2025-07-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_alter_informes_id_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoserviciospublicos',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
