# Generated by Django 5.2.4 on 2025-08-21 16:16

import apy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_alter_pagoserviciospublicos_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[apy.models.validar_monto]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagoserviciospublicos',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[apy.models.validar_monto]),
        ),
    ]
