# Generated by Django 5.2.4 on 2025-07-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_rename_id_vehiculo_salidavehiculo_idss_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidavehiculo',
            old_name='idss_vehiculo',
            new_name='id_vehiculo',
        ),
    ]
