# Generated by Django 5.2.4 on 2025-07-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_rename_correo_empleado_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gastos',
            name='id_pagos_servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.pagoserviciospublicos'),
        ),
    ]
