# Generated by Django 5.2.4 on 2025-08-12 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_repuesto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apy.proveedores'),
        ),
        migrations.AlterField(
            model_name='entradavehiculo',
            name='id_cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apy.cliente'),
        ),
        migrations.AlterField(
            model_name='entradavehiculo',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo'),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='id_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.marca'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='id_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.marca'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='id_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apy.marca'),
        ),
        migrations.AlterField(
            model_name='salidavehiculo',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apy.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='id_cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apy.cliente'),
        ),
    ]
