# Generated by Django 5.2.4 on 2025-08-19 13:06

import apy.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0003_alter_administrador_correo_alter_proveedores_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='apellidos',
            field=models.CharField(error_messages={'blank': 'El apellido es obligatorio'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(error_messages={'blank': 'El correo es obligatorio', 'invalid': 'El correo no tiene un formato válido', 'unique': 'Ya existe un administrador con ese correo'}, max_length=254, unique=True, validators=[apy.models.validar_email]),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='edad',
            field=models.PositiveIntegerField(error_messages={'blank': 'La edad es obligatoria'}),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='fecha_ingreso',
            field=models.DateField(error_messages={'blank': 'La fecha de ingreso es obligatoria'}),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='identificacion',
            field=models.BigIntegerField(error_messages={'blank': 'La identificación es obligatoria', 'unique': 'Ya existe un administrador con esa identificación'}, unique=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(error_messages={'blank': 'El nombre es obligatorio'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(error_messages={'blank': 'El teléfono es obligatorio'}, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números y tener entre 7 y 10 dígitos.', regex='^\\d{7,10}$')]),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números y tener entre 7 y 10 dígitos.', regex='^\\d{7,10}$')]),
        ),
    ]
