# Generated by Django 5.2.4 on 2025-07-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0004_rename_idss_vehiculo_salidavehiculo_id_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradavehiculo',
            old_name='id_vehiculo',
            new_name='ids_vehiculo',
        ),
    ]
