# Generated by Django 5.2.4 on 2025-08-26 12:15

import apy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0004_factura_monto_alter_pagoserviciospublicos_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[apy.models.validar_monto]),
        ),
    ]
