# Generated by Django 5.2.4 on 2025-07-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0004_pagoserviciospublicos_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='id_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.administrador'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_herramienta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.herramienta'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_insumos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.insumos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.proveedores'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_repuestos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.repuesto'),
        ),
    ]
