# Generated by Django 5.2.4 on 2025-08-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0005_alter_pagos_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='stock_minimo',
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
