# Generated by Django 5.2.4 on 2025-07-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0005_rename_id_vehiculo_entradavehiculo_ids_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradavehiculo',
            old_name='ids_vehiculo',
            new_name='id_vehiculo',
        ),
    ]
