# Generated by Django 5.2.4 on 2025-07-17 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0005_alter_pagos_id_admin_alter_pagos_id_herramienta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='id_herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.herramienta'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_insumos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.insumos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_repuestos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apy.repuesto'),
        ),
    ]
