# Generated by Django 5.2.4 on 2025-07-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0006_alter_pagos_id_herramienta_alter_pagos_id_insumos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
