# Generated by Django 5.2.4 on 2025-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0006_remove_repuesto_stock_minimo_alter_herramienta_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Ingrese un número válido para el precio.', 'required': 'El precio del repuesto es obligatorio.'}, max_digits=10),
        ),
    ]
