# Generated by Django 5.2.4 on 2025-07-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0006_rename_ids_vehiculo_entradavehiculo_id_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id',
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_compra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
