# Generated by Django 5.2.4 on 2025-07-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0007_remove_compra_id_alter_compra_id_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='id_compra',
            new_name='idss_compra',
        ),
    ]
