# Generated by Django 5.2.4 on 2025-08-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0007_alter_repuesto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='costo',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el costo.', 'required': 'Elcosto del insumo es obligatorio.'}),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un número válido para el precio.', 'required': 'El precio del repuesto es obligatorio.'}),
        ),
    ]
