# Generated by Django 5.2.4 on 2025-07-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0008_rename_id_compra_compra_idss_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='idss_compra',
            new_name='id_compra',
        ),
    ]
